---
resources:
  - name: git
    icon: github
    type: git
    source:
      uri: https://github.com/Prafulchouhan/MockQ
      branch: main
  - name: image
    type: registry-image
    icon: docker
    source:
      repository: ((image-name))
      username: ((registry-username))
      password: ((registry-password))
      tag: latest

jobs:
  - name: unit
    plan:
      - get: git
        trigger: true
      - task: run-unit-tests
#        file: git/ci/tasks/test.yml
#        outputs:
#          - name: build
        config:
          platform: linux
          container_limits: { }

          # Use the 'maven:4.0.0' image from Docker Hub
          image_resource:
            type: registry-image
            source:
              repository: maven
              tag: 3.8.4

          # Cache the Maven repository directory
          caches:
            - path: $HOME/.m2/repository

          # We will provide an input called 'src' to this Task
          inputs:
            - name: git
          outputs:
            - name: build

          # What do we want this task to do?
          # Tell Concourse the commands it should execute, in this Task
          run:
            path: /bin/sh
            args:
              - -c
              - |
                mvn -f git/pom.xml clean install

                # Make this output available to the 'test' Job
                cp -R git/* build


  - name: mvn-build
    plan:
      - get: git
        passed:
          - unit
        trigger: true
      - task: test
        config:
          platform: linux
          container_limits: { }
          image_resource:
            type: registry-image
            source:
              repository: maven
              tag: 3.8.4
          caches:
            - path: $HOME/.m2/repository
          inputs:
            - name: git
          outputs:
            - name: package
          run:
            path: /bin/sh
            args:
              - -c
              - |
                mvn -f git/pom.xml clean install
                
                # Make this output available to the 'test' Job
                cp -R git/* package
                
                

      - task: build-task-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
          inputs:
            - name: package
          outputs:
            - name: image
          params:
            CONTEXT: package
          run:
            path: build
      - put: image
        params:
          image: image/image.tar
